if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="Napkin-45C";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

import extras;
size(6cm);
usepackage("amsmath");
usepackage("amssymb");
defaultpen(fontsize(11pt));
settings.tex = "latex";
settings.outformat = "pdf";

size(7cm);
pen e1 = heavyred;
pen e2 = orange;
pen e3 = olive;
pen e4 = heavymagenta;
draw((0,0)--(2,0), e1, EndArrow);
draw((2,0)--(2,2), e2, EndArrow);
draw((2,2)--(0,2), e3, EndArrow);
draw((0,2)--(0,0), e4, EndArrow);
label(scale(0.8)*"$[0,1]^2$", (1,1));
draw( (3,1)--(6,1), EndArrow);
label("$c$", (4.5,1), dir(90));
pair p1 = (7,-1);
pair p2 = (12,-2);
pair p3 = (11,3);
pair p4 = (8,2);
fill(p1--p2--p3--p4--cycle, palecyan);
draw(p1--p2, e1, EndArrow, Margins);
draw(p2--p3, e2, EndArrow, Margins);
draw(p3--p4, e3, EndArrow, Margins);
draw(p4--p1, e4, EndArrow, Margins);
dot("$p_1$", p1, dir(225), blue+4);
dot("$p_2$", p2, dir(315), blue+4);
dot("$p_3$", p3, dir( 45), blue+4);
dot("$p_4$", p4, dir(135), blue+4);
label("$c$", (p1+p2+p3+p4)/4);
