if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="Napkin-80C";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

import extras;
size(6cm);
usepackage("amsmath");
usepackage("amssymb");
defaultpen(fontsize(11pt));
settings.tex = "latex";
settings.outformat = "pdf";

filldraw(unitcircle, opacity(0.2)+lightcyan, blue);
pair A = dir(110);
pair B = dir(210);
pair C = dir(40);
pair D = dir(270);
pair E = dir(130);
pair F = dir(-30);

pair P = extension(A, B, D, E);
pair X = extension(B, C, E, F);
pair Q = extension(C, D, F, A);

draw(A--B--C--D--E--F--cycle);
draw(P--Q, red+dashed);

dot("$A$", A, dir(A));
dot("$B$", B, dir(B));
dot("$C$", C, dir(C));
dot("$D$", D, dir(D));
dot("$E$", E, dir(E));
dot("$F$", F, dir(F));
dot(P);
dot(X);
dot(Q);

/* Source generated by TSQ */
