if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="Napkin-87B";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

import extras;
size(6cm);
usepackage("amsmath");
usepackage("amssymb");
defaultpen(fontsize(11pt));
settings.tex = "latex";
settings.outformat = "pdf";

size(10cm);
pair p = (-4,0);
pair q = ( 4,0);
filldraw(ellipse(p, 2, 1 ), opacity(0.2)+lightcyan, black);
filldraw(ellipse(q, 2, 1 ), opacity(0.2)+lightcyan, black);
label("$X$", p+dir(270), dir(270), blue);
label("$Y$", q+dir(270), dir(270), blue);
pair pt = (-4, 3.5);
pair qt = ( 4, 4.3);
draw( p--pt, red );
draw( q--qt, red );
label("$\mathcal O_{X,p}$", pt, dir(90), red);
label("$\mathcal O_{Y,q}$", qt, dir(90), red);
dot("$p$", p, dir(-90), blue);
dot("$q$", q, dir(-90), blue);
pair pg = (-4, 1.6);
pair qg = (4, 2.8);
dot("$[s]_q$", qg, dir(0), red+6);
dot("$[\pi^\sharp(s)]_p$", pg, dir(180), red+6);
draw(qg--pg, deepgreen, EndArrow, Margin(4,4));
label("$\pi^\sharp_p$", midpoint(qg--pg), dir(90), deepgreen);
draw( (-1.5,0)--(1.5,0), deepgreen, EndArrow );
label("$\pi$", origin, dir(-90), deepgreen);
