name: Napkin CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Compile document"
    permissions:
      actions: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive
          persist-credentials: false
      - name: Install TeX Live
        run: |
          sudo apt update
          sudo apt install -y biber texlive-base texlive-latex-recommended texlive-latex-extra texlive-science
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.14"
      - name: Install more packages
        uses: awalsh128/cache-apt-pkgs-action@2c09a5e66da6c8016428a2172bd76e5e4f14bb17 # latest
        with:
          packages: |
            latexmk asymptote ghostscript qpdf

      - name: Restore cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          key: "napkin-cache"
          path: |
            **/*.aux
            **/*.out
            Napkin.bbl
            Napkin.bcf
            Napkin.blg
            Napkin.fdb_latexmk
            Napkin.fls
            Napkin.log
            Napkin.maf
            Napkin.mtc
            Napkin.mtc0
            Napkin.pre
            Napkin.ptc*
            Napkin.run.xml
            Napkin.synctex.gz
            Napkin.toc
            asy/Napkin-*.asy
            asy/Napkin-*.pdf
      - name: Compile document
        run: latexmk -pdflatex -interaction=nonstopmode -file-line-error Napkin.tex
      - name: Save cache
        uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          key: "napkin-cache"
          path: |
            **/*.aux
            **/*.out
            Napkin.bbl
            Napkin.bcf
            Napkin.blg
            Napkin.fdb_latexmk
            Napkin.fls
            Napkin.log
            Napkin.maf
            Napkin.mtc
            Napkin.mtc0
            Napkin.pre
            Napkin.ptc*
            Napkin.run.xml
            Napkin.synctex.gz
            Napkin.toc
            asy/Napkin-*.asy
            asy/Napkin-*.pdf

      - name: Compile flowchart
        run: |
          ./export-flowchart.sh
      - name: Extract table of contents
        run: |
          python3 print-toc.py --parts --chapters --numbers > toc.txt
      - name: Extract per-part PDF's
        run: |
          python3 print-toc.py --qpdf | bash

      - name: Create dist folder
        run: |
          mkdir -p dist
          mkdir -p dist/figures
          mkdir -p dist/Parts/

          cp Napkin.log dist/
          cp Napkin.pdf dist/
          cp asy/*.asy dist/figures/
          cp asy/*.pdf dist/figures/
          cp cover-art.png dist/
          cp cover-art.jpg dist/

          mv flowchart.png dist/
          mv toc.txt dist/
          mv part-*.pdf dist/Parts

          cd dist
          tree -H '.' -I "index.html" -D --charset utf-8 --filesfirst -T "An Infinitely Large Napkin: All Generated Files" >index.html
      - name: Setup Pages
        uses: actions/configure-pages@b8130d9ab958b325bbde9786d62f2c97a9885a0e # v3
      - name: Upload PDF artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          path: Napkin.pdf
          name: Napkin.pdf
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    name: "Deploy to GitHub Pages"
    needs: build
    permissions:
      actions: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
